spring:
  application:
    name: trabalhoDBII
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trabalhoDBII
      username: trabalhoDBII
      password: trabalhoDBII# (Optional) Password for authentication
      authentication-database: admin
      uri: mongodb://trabalhoBDII:trabalhoBDII@localhost:27017/trabalhoDBII?authSource=admin